# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Сборка проекта Lab1
    - name: Configure CMake for Lab1 (Linear algebra)
      run: cmake -S "Linear algebra/Lab1 (Direct methods for solving systems of linear equations)/src" -B "Linear algebra/Lab1 (Direct methods for solving systems of linear equations)/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Lab1 (Linear algebra)
      run: cmake --build "Linear algebra/Lab1 (Direct methods for solving systems of linear equations)/build" --config ${{env.BUILD_TYPE}}

    - name: Test Lab1 (Linear algebra)
      working-directory: "Linear algebra/Lab1 (Direct methods for solving systems of linear equations)/build"
      run: ctest -C ${{env.BUILD_TYPE}}

    # Сборка проекта Lab2
    - name: Configure CMake for Lab2 (Linear algebra)
      run: cmake -S "Linear algebra/Lab2 (Iterative methods for solving systems of linear equations)/src" -B "Linear algebra/Lab2 (Iterative methods for solving systems of linear equations)/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Lab2 (Linear algebra)
      run: cmake --build "Linear algebra/Lab2 (Iterative methods for solving systems of linear equations)/build" --config ${{env.BUILD_TYPE}}

    - name: Test Lab2 (Linear algebra)
      working-directory: "Linear algebra/Lab2 (Iterative methods for solving systems of linear equations)/build"
      run: ctest -C ${{env.BUILD_TYPE}}

    # Сборка проекта Lab3
    - name: Configure CMake for Lab3 (Linear algebra)
      run: cmake -S "Linear algebra/Lab3 (Solving interpolation problems)/src" -B "Linear algebra/Lab3 (Solving interpolation problems)/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Lab3 (Linear algebra)
      run: cmake --build "Linear algebra/Lab3 (Solving interpolation problems)/build" --config ${{env.BUILD_TYPE}}

    - name: Test Lab3 (Linear algebra)
      working-directory: "Linear algebra/Lab3 (Solving interpolation problems)/build"
      run: ctest -C ${{env.BUILD_TYPE}}
      
    # Сборка проекта Lab4
    - name: Configure CMake for Lab4 (Linear algebra)
      run: cmake -S "Linear algebra/Lab4 (Solving the eigenvalue problem)/src" -B "Linear algebra/Lab4 (Solving the eigenvalue problem)/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Lab4 (Linear algebra)
      run: cmake --build "Linear algebra/Lab4 (Solving the eigenvalue problem)/build" --config ${{env.BUILD_TYPE}}

    - name: Test Lab4 (Linear algebra)
      working-directory: "Linear algebra/Lab4 (Solving the eigenvalue problem)/build"
      run: ctest -C ${{env.BUILD_TYPE}}
      
      # Сборка проекта Lab5
    - name: Configure CMake for Lab5 (Linear algebra)
      run: cmake -S "Linear algebra/Lab5 (Solving nonlinear equations)/src" -B "Linear algebra/Lab5 (Solving nonlinear equations)/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Lab5 (Linear algebra)
      run: cmake --build "Linear algebra/Lab5 (Solving nonlinear equations)/build" --config ${{env.BUILD_TYPE}}

    - name: Test Lab5 (Linear algebra)
      working-directory: "Linear algebra/Lab5 (Solving nonlinear equations)/build"
      run: ctest -C ${{env.BUILD_TYPE}}

# Сборка проекта Lab1
    - name: Configure CMake for Lab1 (Mathematical physics)
      run: cmake -S "Mathematical physics/Lab1 (Numerical methods for solving ordinary differential equations)/src" -B "Mathematical physics/Lab1 (Numerical methods for solving ordinary differential equations)/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Lab1 (Mathematical physics)
      run: cmake --build "Mathematical physics/Lab1 (Numerical methods for solving ordinary differential equations)/build" --config ${{env.BUILD_TYPE}}

    - name: Test Lab1 (Mathematical physics)
      working-directory: "Mathematical physics/Lab1 (Numerical methods for solving ordinary differential equations)/build"
      run: ctest -C ${{env.BUILD_TYPE}}
